test: fix multi_pmem link error
As reported by issue #8:

  "I tried to build ndctl, and I executed "make check",
   but I met link error of libuuid like followings.

    /usr/bin/ld: multi-pmem.o: undefined reference to symbol 'uuid_unparse@@UUID_1.0'
    /lib/x86_64-linux-gnu/libuuid.so.1: error adding symbols: DSO missing from command line

   Not only libuuid, but also libkmod has similar problem."

Add the missing libraries to the dependency list. This happens to work
on latest Fedora, but fails for the reporter on Ubuntu 14.04.

Link: https://github.com/pmem/ndctl/issues/8
Reported-by: Yasunori Goto <y-goto@jp.fujitsu.com>
Tested-by: Yasunori Goto <y-goto@jp.fujitsu.com>
Signed-off-by: Dan Williams <dan.j.williams@intel.com>